content/docs/features/virtual-branches/overview.mdx
There was no link to the doc that explains how to switch between traditional Git and GitButler
Replace static text with a markdown link
=> fix: add link to integration docs

content/docs/releases.mdx
- Bump releases on `releases.mdx` manually
=> fix: manually bump releases.mdx page for now

content/docs/features/virtual-branches/commits.mdx
- Add info about the variables (i.e. `%{brief_style}`) available in the commit message prompt
Fixes #18
=> fix: add info about AI commit msg variables

.github/broken-link-checker/src/index.ts
- Whenever new pages are added, they will by definition not be available under the `github.com/gitbutlerapp/gitbutler-docs/blob/main/...` links until the PR is merged.
- Therefore they'll always be  marked as "Broken" by the broken-link-checker action
- Whitelist links with the Keywrods `"Edit on GitHub"` and `"https ://github.com/gitbutlerapp/gitbutler-docs/blob/main/content/docs"`
=> fix: whitelist 'Edit on GitHub' links for broken-link-checker

app/components/ImageSection.tsx
- Image height broken on Safari
- Remove unnecessary `height: 'fit-content'` (`h-fit`)
=> fix: rm unnecessary h-fit

content/docs/features/virtual-branches/butler-flow.mdx
Add an apostrophe to indicate a plural possessive noun for clearer reading.
`"coworkers" --> "coworkers'"`
=> fix: grammar

content/docs/development/debugging.mdx
The log path is wrong.
Here I found the logs:
Fix path displayed to user.
=> Fix path to logs

content/docs/releases.mdx
- Fix typo in "link issue" to "pinned issue" for Tauri issue URL
=> fix: typo in releases.mdx page

content/docs/troubleshooting/fetch-push.mdx
When trying to use GitButler for repositories under GitHub organizations with OAuth app access restrictions (enabled by default when creating new GitHub organizations), GitButler provides an error when trying to perform any action on the remote indicating that, despite having correct authorization credentials, third-party app access to the organization's repository is restricted.
Currently, there is no documentation provided to resolve this issue.
Add a section to the troubleshooting section under "Fetch/push" addressing this issue and how to resolve it, with notes for organization owners.
Fixes: #45
=> docs: add section on GitHub OAuth app access troubleshooting.

package.json, pnpm-lock.yaml, scripts/generate-docs.mjs
- Improve workaround to not delete Project entities from OpenAPI entities that have cyclic references to projects
- Set title on the entities instead of deleting the `project` property (See: https://github.com/fuma-nama/fumadocs/issues/1100#issuecomment-2503880111)
=> fix: bump fumadocs-openapi and rm workaround for cyclic references

content/docs/meta.json
- API Reference was growing to be just internal API endpoints, so more confusing for users than anything else
- Remove "API Reference" link from sidebar for now
=> fix: hide API Reference from sidebar

content/docs/development/debugging.mdx
On my Windows machine since ~2 weeks all new log files are written to `Local` and not to `Roaming`. Maybe something changed?
Replaced `Roaming` with `Local`. Maybe it is not so easy and both paths need to be displayed..
=> Fix old? log directory on Windows

content/docs/development/debugging.mdx
Inspired by [this comment](https://github.com/gitbutlerapp/gitbutler/issues/5740#issuecomment-2519286594) over at GitButler, it was shown that on Linux the log-location is more diverse.
Let's inform about this to make log-retrieval on Linux easier.
=> Provide alternative log location for linux

content/docs/features/virtual-branches/branch-lanes.mdx
=> chore: update branch-lanes.mdx typo

content/docs/features/virtual-branches/integration-branch.mdx
GitButler's integration branch name was renamed in the following Pull Request.
https://github.com/gitbutlerapp/gitbutler/pull/4729
The text in the document should be updated to the new one.
Rename the integration branch name from `gitbutler/integration` to `gitbutler/workspace` in the following page.
- Virtual Branches -> Integration Branches
**NOTE:** 
The file `recovering-stuff.mdx` was not changed because it contains the string `gitbutler/integration` as part of a git log message.
=> Update integration branch name to the new one.

content/docs/development/debugging.mdx, content/docs/features/virtual-branches/signing-commits.mdx, content/docs/troubleshooting/recovering-stuff.mdx
- Update `gitbutler/integration` -> `gitbutler/workspace`
- Update path segment `com.gitbutler.app` -> `gitbutler-tauri` ~(**Needs verification on Mac OS**)~ on Linux only
- Add a few common linux debugging notes
=> fix: update references to integration branch and gitbutler binary in paths + Linux debug notes

app/layout.tsx
In our search results, the docs pages comes up as just "GitButler", which is a little confusing.
=> Add docs to descriptions

content/docs/features/virtual-branches/integration-branch.mdx
=> docs: fix grammar

content/docs/features/virtual-branches/signing-commits.mdx
Related to https://github.com/gitbutlerapp/gitbutler/issues/5661.
=> Clarify how `gitbutler.signCommits` affects commit signatures.

vercel.json
This pull request updates the routing rules in `vercel.json` to improve how requests for virtual branches features are redirected. The main change is replacing a specific redirect with a more flexible pattern to ensure all relevant paths are correctly routed.
Routing improvements:
* Removed the explicit redirect from `/features/virtual-branches` to `/features/branch-management/virtual-branches`, and replaced it with a wildcard redirect from `/features/virtual-branches/:path*` to `/features/branch-management/:path*`, allowing all subpaths to be redirected appropriately.
=> add path fallback for "/virtual-branches/"
